# OpenAI Gym and Python for Q-learning

In [1]:
!pip install gym

# Notebook Imports

In [2]:
import numpy as np
import gymnasium as gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make('FrozenLake-v1')

In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Constants

In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001    

# Q-learning algorithm

In [6]:
rewards_all_episodes = []

# Q-learning Algorithm
for episode in range(num_episodes):
    state = env.reset()[0]
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, truncated, info = env.step(action)
        
        # Update Q-table for Q(s, a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :])) 
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
    # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
# Calculate the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print('*****Average reward per Thousand*****\n')

for r in rewards_per_thousand_episodes:
    print(f'{count}: {sum(r/1000)}')
    count+=1000
    
# Print updated Q-table
print('\n\n*****Q-table*****\n')
print(q_table)

*****Average reward per Thousand*****

1000: 0.047000000000000035
2000: 0.19300000000000014
3000: 0.4140000000000003
4000: 0.5480000000000004
5000: 0.6270000000000004
6000: 0.6610000000000005
7000: 0.6830000000000005
8000: 0.6750000000000005
9000: 0.6830000000000005
10000: 0.6800000000000005


*****Q-table*****

[[0.48701172 0.48402856 0.48404465 0.48481016]
 [0.28790389 0.38058772 0.18101397 0.46619583]
 [0.41501799 0.40599876 0.41697895 0.44204726]
 [0.26024489 0.15837628 0.34196834 0.43581914]
 [0.49233502 0.47778461 0.46476748 0.32291719]
 [0.         0.         0.         0.        ]
 [0.17151328 0.10655058 0.27382629 0.06659406]
 [0.         0.         0.         0.        ]
 [0.51104664 0.38122017 0.3761096  0.5156652 ]
 [0.41159767 0.56698805 0.53333565 0.40248811]
 [0.4903133  0.36986523 0.30617283 0.19113229]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.57272545 0.57667072 0.63999847 0.54842021]
 [0.74942169 0.86832638 0.73

In [7]:
for episode in range(3):
    state = env.reset()[0]
    done = False
    print(f'*****EPISODE: {episode+1} *****\n\n\n\n')
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])
        new_state, reward, done, truncated, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            
            if reward == 1:
                print('****You reached the goal!!!*****')
                time.sleep(3)
                
            else:
                print('****You fell through a hole!****')
                time.sleep(3)
            clear_output(wait=True)
            break
            
        state = new_state
        
env.close()

****You reached the goal!!!*****
